//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.Stock
{

public sealed partial class Dice :  Bright.Config.BeanBase 
{
    public Dice(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["en_name"].IsString) { throw new SerializationException(); }  EnName = _json["en_name"]; }
        { if(!_json["zh_name"].IsString) { throw new SerializationException(); }  ZhName = _json["zh_name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        PostInit();
    }

    public Dice(int id, string en_name, string zh_name, string desc ) 
    {
        this.Id = id;
        this.EnName = en_name;
        this.ZhName = zh_name;
        this.Desc = desc;
        PostInit();
    }

    public static Dice DeserializeDice(JSONNode _json)
    {
        return new Stock.Dice(_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 英文名
    /// </summary>
    public string EnName { get; private set; }
    /// <summary>
    /// 中文名
    /// </summary>
    public string ZhName { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }

    public const int __ID__ = -1682138177;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EnName:" + EnName + ","
        + "ZhName:" + ZhName + ","
        + "Desc:" + Desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
