//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.Stock
{

public sealed partial class Item :  Bright.Config.BeanBase 
{
    public Item(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["zh_name"].IsString) { throw new SerializationException(); }  ZhName = _json["zh_name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  Type = (ItemEnum.ItemType)_json["type"].AsInt; }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  Price = _json["price"]; }
        { if(!_json["max_overlap"].IsNumber) { throw new SerializationException(); }  MaxOverlap = _json["max_overlap"]; }
        { if(!_json["upgrade_to_item_id"].IsNumber) { throw new SerializationException(); }  UpgradeToItemId = _json["upgrade_to_item_id"]; }
        { if(!_json["can_interact"].IsBoolean) { throw new SerializationException(); }  CanInteract = _json["can_interact"]; }
        { if(!_json["color"].IsNumber) { throw new SerializationException(); }  Color = (ItemEnum.HighLightColor)_json["color"].AsInt; }
        PostInit();
    }

    public Item(int id, string name, string zh_name, string desc, ItemEnum.ItemType type, int price, int max_overlap, int upgrade_to_item_id, bool can_interact, ItemEnum.HighLightColor color ) 
    {
        this.Id = id;
        this.Name = name;
        this.ZhName = zh_name;
        this.Desc = desc;
        this.Type = type;
        this.Price = price;
        this.MaxOverlap = max_overlap;
        this.UpgradeToItemId = upgrade_to_item_id;
        this.CanInteract = can_interact;
        this.Color = color;
        PostInit();
    }

    public static Item DeserializeItem(JSONNode _json)
    {
        return new Stock.Item(_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 英文名
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 中文名
    /// </summary>
    public string ZhName { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public ItemEnum.ItemType Type { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int Price { get; private set; }
    /// <summary>
    /// 最大堆叠数目
    /// </summary>
    public int MaxOverlap { get; private set; }
    /// <summary>
    /// 引用当前表
    /// </summary>
    public int UpgradeToItemId { get; private set; }
    public Stock.Item UpgradeToItemId_Ref { get; private set; }
    /// <summary>
    /// 能否互动
    /// </summary>
    public bool CanInteract { get; private set; }
    /// <summary>
    /// 场景中的高亮颜色
    /// </summary>
    public ItemEnum.HighLightColor Color { get; private set; }

    public const int __ID__ = -1681978581;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.UpgradeToItemId_Ref = (_tables["Stock.TbItem"] as Stock.TbItem).GetOrDefault(UpgradeToItemId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ZhName:" + ZhName + ","
        + "Desc:" + Desc + ","
        + "Type:" + Type + ","
        + "Price:" + Price + ","
        + "MaxOverlap:" + MaxOverlap + ","
        + "UpgradeToItemId:" + UpgradeToItemId + ","
        + "CanInteract:" + CanInteract + ","
        + "Color:" + Color + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
