//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.DataTable
{

public sealed partial class DefaultSetting :  Bright.Config.BeanBase 
{
    public DefaultSetting(JSONNode _json) 
    {
        { if(!_json["guild_open_level"].IsNumber) { throw new SerializationException(); }  GuildOpenLevel = _json["guild_open_level"]; }
        { if(!_json["bag_init_capacity"].IsNumber) { throw new SerializationException(); }  BagInitCapacity = _json["bag_init_capacity"]; }
        { if(!_json["bag_max_capacity"].IsNumber) { throw new SerializationException(); }  BagMaxCapacity = _json["bag_max_capacity"]; }
        { var __json0 = _json["newbie_tasks"]; if(!__json0.IsArray) { throw new SerializationException(); } NewbieTasks = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NewbieTasks.Add(__v0); }   }
        PostInit();
    }

    public DefaultSetting(int guild_open_level, int bag_init_capacity, int bag_max_capacity, System.Collections.Generic.List<int> newbie_tasks ) 
    {
        this.GuildOpenLevel = guild_open_level;
        this.BagInitCapacity = bag_init_capacity;
        this.BagMaxCapacity = bag_max_capacity;
        this.NewbieTasks = newbie_tasks;
        PostInit();
    }

    public static DefaultSetting DeserializeDefaultSetting(JSONNode _json)
    {
        return new DataTable.DefaultSetting(_json);
    }

    /// <summary>
    /// desc1
    /// </summary>
    public int GuildOpenLevel { get; private set; }
    /// <summary>
    /// desc 2
    /// </summary>
    public int BagInitCapacity { get; private set; }
    /// <summary>
    /// desc 3
    /// </summary>
    public int BagMaxCapacity { get; private set; }
    /// <summary>
    /// desc 4
    /// </summary>
    public System.Collections.Generic.List<int> NewbieTasks { get; private set; }

    public const int __ID__ = -738060807;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GuildOpenLevel:" + GuildOpenLevel + ","
        + "BagInitCapacity:" + BagInitCapacity + ","
        + "BagMaxCapacity:" + BagMaxCapacity + ","
        + "NewbieTasks:" + Bright.Common.StringUtil.CollectionToString(NewbieTasks) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
