//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.DataTable
{

public sealed partial class EntityConfig :  Bright.Config.BeanBase 
{
    public EntityConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _json["asset_name"]; }
        PostInit();
    }

    public EntityConfig(int id, string asset_name ) 
    {
        this.Id = id;
        this.AssetName = asset_name;
        PostInit();
    }

    public static EntityConfig DeserializeEntityConfig(JSONNode _json)
    {
        return new DataTable.EntityConfig(_json);
    }

    /// <summary>
    /// 实体编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源名
    /// </summary>
    public string AssetName { get; private set; }

    public const int __ID__ = -921993041;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
