//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.DataTable
{

public sealed partial class TbDefaultSetting
{
    private readonly Dictionary<int, DataTable.DefaultSetting> _dataMap;
    private readonly List<DataTable.DefaultSetting> _dataList;
    
    public TbDefaultSetting(JSONNode _json)
    {
        _dataMap = new Dictionary<int, DataTable.DefaultSetting>();
        _dataList = new List<DataTable.DefaultSetting>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = DataTable.DefaultSetting.DeserializeDefaultSetting(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.GuildOpenLevel, _v);
        }
        PostInit();
    }

    public Dictionary<int, DataTable.DefaultSetting> DataMap => _dataMap;
    public List<DataTable.DefaultSetting> DataList => _dataList;

    public DataTable.DefaultSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataTable.DefaultSetting Get(int key) => _dataMap[key];
    public DataTable.DefaultSetting this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}