//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace LubanConfig.DataTable
{

public sealed partial class TbEntityConfig
{
    private readonly List<DataTable.EntityConfig> _dataList;
    
    private Dictionary<int, DataTable.EntityConfig> _dataMap_id;
    private Dictionary<string, DataTable.EntityConfig> _dataMap_asset_name;

    public TbEntityConfig(JSONNode _json)
    {
        _dataList = new List<DataTable.EntityConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = DataTable.EntityConfig.DeserializeEntityConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, DataTable.EntityConfig>();
        _dataMap_asset_name = new Dictionary<string, DataTable.EntityConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_asset_name.Add(_v.AssetName, _v);
    }
        PostInit();
    }

    public List<DataTable.EntityConfig> DataList => _dataList;

    public DataTable.EntityConfig GetById(int key) => _dataMap_id.TryGetValue(key, out DataTable.EntityConfig __v) ? __v : null;
    public DataTable.EntityConfig GetByAssetName(string key) => _dataMap_asset_name.TryGetValue(key, out DataTable.EntityConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}